drop index reprimand_issue_date_to_char_idx;
drop index sentence_start_date_to_char_idx;
drop index sentence_real_end_date_to_char_idx;
drop index accommodation_start_date_to_char_idx;
drop index accommodation_end_date_to_char_idx;
drop index patrol_slot_start_time_to_char_idx;
drop index patrol_slot_end_time_to_char_idx;
